backend:
  name: github
  repo: davutkara/davutkara.com
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'static/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Resume Page'
        name: 'about'
        file: 'assets/content/resume.yaml'
        fields:
          - {
              label: Education Title,
              name: education-title,
              widget: string,
              defaults: 'EDUCATION',
            }
          - label: Education List
            name: educatıon-list
            widget: list
            fields:
              - { label: University, name: university, widget: string }
              - { label: department, name: photo, widget: string }
              - label: Lines
                name: lines
                widget: list
                fields:
                  - { label: line, name: line, widget: string }
          - {
              label: Links Title,
              name: links-title,
              widget: string,
              defaults: 'LINKS',
            }
          - label: Link List
            name: link-list
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: url, name: url, widget: string }
              - { label: name, name: name, widget: string }
          - {
              label: Commuication Title,
              name: communication-title,
              widget: string,
              defaults: 'COMMUNICATION',
            }
          - {
              label: Mother Language Title,
              name: mother-language-title,
              widget: string,
              defaults: 'Mother Language',
            }
          - {
              label: Mother Language,
              name: mother-language,
              widget: string,
              defaults: 'Turkish',
            }
          - {
              label: Foreign Language Title,
              name: foreign-language-title,
              widget: string,
              defaults: 'Foreign Languages',
            }
          - label: Foreign Languages List
            name: foreign-language-list
            widget: list
            fields:
              - { label: Language, name: language, widget: string }
          - {
              label: SKills Title,
              name: skills-title,
              widget: string,
              defaults: 'SKILLS',
            }
          - label: SKILLS List
            name: skills-list
            widget: list
            fields:
              - { label: Skill, name: skill, widget: string }
              - {
                  label: Points,
                  name: points,
                  widget: number,
                  min: 0,
                  max: 100,
                  step: 5,
                  valueType: int,
                  default: 50,
                }
          - {
              label: Experience Title,
              name: experience-title,
              widget: string,
              defaults: 'EXPERIENCE',
            }
          - label: Experience List
            name: experience-list
            widget: list
            fields:
              - { label: Experience Title, name: title, widget: string }
              - { label: Experience Position, name: position, widget: string }
              - {
                  label: Start Date,
                  name: startDate,
                  widget: datetime,
                  dateFormat: 'MMM YYYY',
                }
              - {
                  label: Finish Date,
                  name: finishDate,
                  widget: datetime,
                  dateFormat: 'MMM YYYY',
                  required: false,
                }
              - { label: Locaition, name: location, widget: string }
              - label: Description List
                name: lines
                widget: list
                fields:
                  - { label: Line, name: line, widget: string }
          - {
              label: Awards Title,
              name: awards-title,
              widget: string,
              defaults: 'AWWARDS',
            }
          - label: Awards List
            name: awards-list
            widget: list
            fields:
              - {
                  label: Year,
                  name: year,
                  widget: datetime,
                  dateFormat: 'YYYY',
                }
              - { label: Description, name: description, widget: string }
              - { label: Url, name: url, widget: string }
