backend:
  name: github
  repo: davutkara/davutkara.com
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'static/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'
collections:
  - name: 'blog-tr'
    label: 'Türkçe Blog'
    create: true
    format: 'yaml'
    folder: 'static/api/content/blog-tr'
    slug: '{{fields.slug}}'
    fields:
      - label: 'Blog Türü'
        name: 'type'
        widget: 'select'
        options:
          - { label: 'Bilişim Hakkında', value: 'ABOUT_IT' }
          - { label: 'Kişisel Şeyler', value: 'ABOUT_PERSONAL' }
          - { label: 'Paylaşım', value: 'FEED' }
          - { label: 'Sözler', value: 'QUOTE' }
      - { label: 'Başlık', name: 'title', widget: 'string', required: true }
      - { label: 'URL Slug', name: 'slug', widget: 'string', required: true }
      - label: 'İngilizce Versiyonu'
        name: 'englishVersionUrl'
        widget: 'relation'
        collection: 'blog-en'
        searchFields: ['title', 'slug']
        valueField: 'slug'
        displayFields: ['title', 'slug']
      - label: 'Ön Görsel'
        name: 'thumbnail'
        widget: 'image'
        required: false
      - {
          label: 'content',
          name: 'content',
          widget: 'markdown',
          required: false,
        }
      - { label: 'author', name: 'author', widget: 'string', required: false }
      - label: 'links'
        name: 'Bağlantılar'
        widget: 'list'
        required: false
        fields:
          - { label: Link Adı, name: name, widget: string }
          - { label: Link URL, name: url, widget: string }
  - label: 'Pages'
    name: 'pages'
    preview_path: resume/
    files:
      - label: 'Resume Page'
        name: 'resume'
        file: 'static/api/content/resume.en.yaml'
        fields:
          - {
              label: Education Title,
              name: education-title,
              widget: string,
              defaults: 'EDUCATION',
            }
          - label: Education List
            name: educatıon-list
            widget: list
            fields:
              - { label: University, name: university, widget: string }
              - { label: Department, name: department, widget: string }
              - label: Lines
                name: lines
                widget: list
                fields:
                  - { label: line, name: line, widget: string }
          - {
              label: Links Title,
              name: links-title,
              widget: string,
              defaults: 'LINKS',
            }
          - label: Link List
            name: link-list
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: url, name: url, widget: string }
              - { label: name, name: name, widget: string }
          - {
              label: Commuication Title,
              name: communication-title,
              widget: string,
              defaults: 'COMMUNICATION',
            }
          - {
              label: Mother Language Title,
              name: mother-language-title,
              widget: string,
              defaults: 'Mother Language',
            }
          - {
              label: Mother Language,
              name: mother-language,
              widget: string,
              defaults: 'Turkish',
            }
          - {
              label: Foreign Language Title,
              name: foreign-language-title,
              widget: string,
              defaults: 'Foreign Languages',
            }
          - label: Foreign Languages List
            name: foreign-language-list
            widget: list
            fields:
              - { label: Language, name: language, widget: string }
          - {
              label: SKills Title,
              name: skills-title,
              widget: string,
              defaults: 'SKILLS',
            }
          - label: SKILLS List
            name: skills-list
            widget: list
            fields:
              - { label: Skill, name: skill, widget: string }
              - {
                  label: Points,
                  name: points,
                  widget: number,
                  min: 0,
                  max: 100,
                  step: 5,
                  valueType: int,
                  default: 50,
                }
          - {
              label: Experience Title,
              name: experience-title,
              widget: string,
              defaults: 'EXPERIENCE',
            }
          - label: Experience List
            name: experience-list
            widget: list
            fields:
              - { label: Experience Title, name: title, widget: string }
              - { label: Experience Position, name: position, widget: string }
              - {
                  label: Start Date,
                  name: startDate,
                  widget: datetime,
                  dateFormat: 'MMM YYYY',
                }
              - {
                  label: Finish Date,
                  name: finishDate,
                  widget: datetime,
                  dateFormat: 'MMM YYYY',
                  required: false,
                }
              - { label: Locaition, name: location, widget: string }
              - label: Description List
                name: lines
                widget: list
                fields:
                  - { label: Line, name: line, widget: string }
          - {
              label: Awards Title,
              name: awards-title,
              widget: string,
              defaults: 'AWWARDS',
            }
          - label: Awards List
            name: awards-list
            widget: list
            fields:
              - {
                  label: Year,
                  name: year,
                  widget: datetime,
                  dateFormat: 'YYYY',
                }
              - { label: Description, name: description, widget: string }
              - { label: Url, name: url, widget: string }
      - label: 'Özgeçmiş Sayfası'
        name: 'ozgecmıs'
        preview_path: tr/ozgecmis
        file: 'static/api/content/resume.tr.yaml'
        fields:
          - {
              label: Eğitim Başlığı,
              name: education-title,
              widget: string,
              defaults: 'EĞİTİM',
            }
          - label: Eğitim Listesi
            name: educatıon-list
            widget: list
            fields:
              - { label: Üniversite, name: university, widget: string }
              - { label: Bölüm, name: department, widget: string }
              - label: Ek satırlar
                name: lines
                widget: list
                fields:
                  - { label: line, name: line, widget: string }
          - {
              label: Bağlantılar Başlığı,
              name: links-title,
              widget: string,
              defaults: 'BAĞLANTILAR',
            }
          - label: Bağlantılar Listesi
            name: link-list
            widget: list
            fields:
              - { label: Başlık, name: title, widget: string }
              - { label: url, name: url, widget: string }
              - { label: kullanıcı adı, name: name, widget: string }
          - {
              label: İletişim Başlığı,
              name: communication-title,
              widget: string,
              defaults: 'İLETİŞİM',
            }
          - {
              label: Ana Dil Başlığı,
              name: mother-language-title,
              widget: string,
              defaults: 'Ana Dil',
            }
          - {
              label: Ana Dil,
              name: mother-language,
              widget: string,
              defaults: 'Türkçe',
            }
          - {
              label: Yabancı Dil Başlığı,
              name: foreign-language-title,
              widget: string,
              defaults: 'Yabancı Diller',
            }
          - label: Yabancı Dil Listesi
            name: foreign-language-list
            widget: list
            fields:
              - { label: Yabancı Dil, name: language, widget: string }
          - {
              label: Yetenekler Başlığı,
              name: skills-title,
              widget: string,
              defaults: 'YETENEKLER',
            }
          - label: Yetenekler Listesi
            name: skills-list
            widget: list
            fields:
              - { label: Yetenek, name: skill, widget: string }
              - {
                  label: Puan,
                  name: points,
                  widget: number,
                  min: 0,
                  max: 100,
                  step: 5,
                  valueType: int,
                  default: 50,
                }
          - {
              label: Deneyimler Başlığı,
              name: experience-title,
              widget: string,
              defaults: 'DENEYİMLER',
            }
          - label: Deneyimler Listesi
            name: experience-list
            widget: list
            fields:
              - { label: Deneyim / Şirket Adı, name: title, widget: string }
              - { label: Deneyim Pozisyonu, name: position, widget: string }
              - {
                  label: Başlama Tarihi,
                  name: startDate,
                  widget: datetime,
                  dateFormat: 'MMM YYYY',
                }
              - {
                  label: Bitirme Tarihi,
                  name: finishDate,
                  widget: datetime,
                  dateFormat: 'MMM YYYY',
                  required: false,
                }
              - { label: Lokasyon, name: location, widget: string }
              - label: Açıklama Listesi
                name: lines
                widget: list
                fields:
                  - { label: Satır, name: line, widget: string }
          - {
              label: Ödüller Başlığı,
              name: awards-title,
              widget: string,
              defaults: 'ÖDÜLLER',
            }
          - label: Ödüller Listesi
            name: awards-list
            widget: list
            fields:
              - {
                  label: Sene,
                  name: year,
                  widget: datetime,
                  dateFormat: 'YYYY',
                }
              - { label: Açıklama, name: description, widget: string }
              - { label: Url, name: url, widget: string }
