backend:
  name: github
  repo: davutkara/davutkara.com
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'static/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Resume Page'
        name: 'about'
        file: 'assets/content/resume.yaml'
        fields:
          - { label: Education, name: education-title, widget: string }
          - label: Education List
            name: educatıon-list
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: University, name: university, widget: string }
              - { label: department, name: photo, widget: image }
              - label: Lines
                name: lines
                widget: list
                fields:
                  - { label: line, name: line, widget: string }
