backend:
  name: github
  repo: davutkara/davutkara.com
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'static/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'
collections:
  - name: 'portfolio' # Used in routes, e.g., /admin/collections/portfolıo
    label: 'Portfolio' # Used in the UI
    folder: '_content/portfolio' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Sub title', name: 'subTitle', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Türkçe İçerik', name: 'body-tr', widget: 'markdown' }
      - { label: 'English Content', name: 'body-en', widget: 'markdown' }
