backend:
  name: github
  repo: davutkara/davutkara.com
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "frontend/public/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img/"
collections:
  - name: "blog-tr"
    label: "Türkçe Blog"
    create: true
    format: "yaml"
    folder: "frontend/public/docs/blog/tr"
    slug: "{{slug}}"
    preview_path: tr/{{slug}}
    fields:
      - { label: "Language", name: "language", widget: "hidden", default: "tr" }
      - { label: "Başlık", name: "title", widget: "string", required: true }
      - { label: "Tags", name: "tags", widget: "string", required: true }
      - { label: "URL Slug", name: "slug", widget: "string", required: true }
      - { label: "Yayınlama Tarihi", name: "date", widget: "datetime" }
      - {
          label: "Aciklama",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "content",
          name: "content",
          widget: "markdown",
          required: false,
        }
      - {
          label: "author",
          name: "author",
          widget: "string",
          default: "Davut KARA",
          required: false,
        }
      - label: "Alternate"
        name: "alternate"
        widget: "object"
        fields:
          - {
              required: false,
              label: "English",
              name: "en",
              widget: "relation",
              collection: "blog-en",
              search_fields: ["title", "slug"],
              value_field: "{{slug}}",
              display_fields: ["language", "slug"],
            }
  - name: "blog-en"
    label: "English Blog"
    create: true
    format: "yaml"
    folder: "frontend/pulic/docs/blog/en"
    slug: "{{slug}}"
    preview_path: /{{slug}}
    fields:
      - { label: "Language", name: "language", widget: "hidden", default: "en" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "URL Slug", name: "slug", widget: "string", required: true }
      - { label: "Tags", name: "tags", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "content",
          name: "content",
          widget: "markdown",
          required: false,
        }
      - {
          label: "author",
          name: "author",
          widget: "string",
          default: "Davut KARA",
          required: false,
        }
      - label: "Alternate"
        name: "alternate"
        widget: "object"
        fields:
          - {
              required: false,
              label: "Turkish",
              name: "tr",
              widget: "relation",
              collection: "blog-tr",
              search_fields: ["title", "slug"],
              value_field: "{{slug}}",
              display_fields: ["language", "slug"],
            }
