backend:
  name: github
  repo: davutkara/davutkara.com
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: 'frontend/public/img' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'
collections:
  - name: 'blog-tr'
    label: 'Türkçe Blog'
    create: true
    format: 'yaml'
    folder: 'frontend/src/assets/docs/blog/tr'
    slug: '{{fields.slug}}'
    preview_path: tr/blog/{{slug}}/?preview=true
    fields:
      - label: 'Blog Türü'
        name: 'type'
        widget: 'select'
        options:
          - { label: 'Bilişim Hakkında', value: 'ABOUT_IT' }
          - { label: 'Kişisel Şeyler', value: 'ABOUT_PERSONAL' }
          - { label: 'Paylaşım', value: 'FEED' }
          - { label: 'Sözler', value: 'QUOTE' }
      - { label: 'Başlık', name: 'title', widget: 'string', required: true }
      - { label: 'URL Slug', name: 'slug', widget: 'string', required: true }
      - { label: 'Yayınlama Tarihi', name: 'date', widget: 'datetime' }
      - label: 'İngilizce Versiyonu'
        name: 'englishVersionUrl'
        widget: 'relation'
        collection: 'blog-en'
        searchFields: ['title', 'slug']
        valueField: 'slug'
        displayFields: ['title', 'slug']
        required: false
      - label: 'Ön Görsel'
        name: 'thumbnail'
        widget: 'image'
        required: false
      - {
          label: 'content',
          name: 'content',
          widget: 'markdown',
          required: false,
        }
      - { label: 'author', name: 'author', widget: 'string', required: false }
      - label: 'Bağlantılar'
        name: 'links'
        widget: 'list'
        required: false
        fields:
          - { label: Link Adı, name: name, widget: string }
          - { label: Link URL, name: url, widget: string }
  - name: 'blog-en'
    label: 'English Blog'
    create: true
    format: 'yaml'
    folder: 'frontend/src/assets/docs/blog/en'
    slug: '{{fields.slug}}'
    preview_path: en/blog/{{slug}}/?preview=true
    fields:
      - label: 'Blog Type'
        name: 'type'
        widget: 'select'
        options:
          - { label: 'About IT', value: 'ABOUT_IT' }
          - { label: 'Blog Posts', value: 'ABOUT_PERSONAL' }
          - { label: 'Feeds', value: 'FEED' }
          - { label: 'Quotes', value: 'QUOTE' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'URL Slug', name: 'slug', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: 'Turkish Version'
        name: 'turkishVersionUrl'
        widget: 'relation'
        collection: 'blog-tr'
        searchFields: ['title', 'slug']
        valueField: 'slug'
        displayFields: ['title', 'slug']
        required: false
      - label: 'Thumbnail'
        name: 'thumbnail'
        widget: 'image'
        required: false
      - {
          label: 'content',
          name: 'content',
          widget: 'markdown',
          required: false,
        }
      - { label: 'author', name: 'author', widget: 'string', required: false }
      - label: 'Links'
        name: 'links'
        widget: 'list'
        required: false
        fields:
          - { label: Link Title, name: name, widget: string }
          - { label: Link URL, name: url, widget: string }